import s from './styles.module.scss'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
   return (
      <>
         <Head>
            <title>Koala Hub</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main className={s.main}>
            <div className={s.description}></div>

            <div className={s.center}>
               <h1 className={s['fortnite-font']}>Koala Hub</h1>
            </div>

            <div className={s.grid}>
               <Link href="" className={s.card} rel="noopener noreferrer">
                  <h2 className={inter.className}>
                     Console! <span>-&gt;</span>
                  </h2>
               </Link>

               <Link
                  href="/pokemon"
                  className={s.card}
                  rel="noopener noreferrer"
               >
                  <h2 className={inter.className}>
                     Pokémon <span>-&gt;</span>
                  </h2>
               </Link>

               <Link href="" className={s.card} rel="noopener noreferrer">
                  <h2 className={inter.className}>
                     Fortnite (Em breve)<span>-&gt;</span>
                  </h2>
               </Link>

               <Link href="" className={s.card}>
                  <h2 className={inter.className}>
                     Onde estacionei meu Uno? (Em breve)<span>-&gt;</span>
                  </h2>
               </Link>
            </div>
         </main>
      </>
   )
}
